# Purpose: This script looks at the robustness index of the seasonal amplitude
# across models / basin / variable. This script produces an .rda object of a list
# that contains the basin / variable sameness(robustness index) line graphs
# and distribution kables.
#
# Created by: Dorheim, Kalyn
# Created on: Nov 14 2017
# Modified:   xxx
#
# Notes: The idea for these figures & analysis came from reading
# https://www.biogeosciences.net/10/6225/2013/
#
# Environment ------------------------------------------------------------------------------

# Required libs
devtools::load_all()
library(dplyr)
library(tidyr)
library(ggplot2)

# Define the package directories where to search for data and save the products
# generated by this script.
INPUT_DIR  <- "data/cmip"
OUTPUT_DIR <- "figs/cmip"

# Print pdf setting, set TRUE or FALSE
please_print <- FALSE



# Script Functions ------------------------------------------------------------------------------
#
# Define the graphing function used by this script. If this turns out to be a
# good function considered adding to R/

# vsis.robustness creates a line graph of the interannual amplitude (seasonal range)
# for various model / basin / variable combinations and compare with with the all
# models mean +/- 1 sd. If a line is outside of this distribution then is it considered
# to unlike the others.

vis.robustness <- function(data){

  # Save the variable name
  vari <- unique(data$variable)

  data %>%
    ggplot(aes(x = year, y = amp_mean)) +
    oceanpH::MY_SETTINGS +
    # Add the individual annual model amplitudes to the graph
    geom_line(aes(x = year, y = amplitude, color = model), size = 0.5) +
    # Add the distribution cloud ribbon thing
    geom_ribbon(aes(ymin = lower_bound, ymax = upper_bound, x=year, linetype=NA),
                alpha = 0.5, color = "grey") +
    geom_line(aes(x = year, y = amp_mean), size = 2) +
   facet_wrap("basin", scales = "free", ncol = 3) +
    labs(title = paste0("Interannual Robustness\n", vari),
         y = paste0(vari, " amplitude"),
         caption = "The shaded grey region is equal to mean +/- sd \n\n") +
    oceanpH::MY_SETTINGS
}


kable.robustness <- function(data, caption = ""){

  # Save the variable name for use in the caption
  vari <- unique(data$variable)

  # Drop the variable column and then make the kable
  data %>%
    select(-variable) %>%
    knitr::kable(format = "html", caption = paste0(vari, " ", caption)) %>%
    kableExtra::kable_styling("striped", full_width = T)
}



# Robustness/Sameness Index  ------------------------------------------------------------------------------

# Import the amplitude data
path <- list.files(INPUT_DIR, "amplitude", full.names = TRUE)
data <- get(load(path)) %>%  ungroup


# Then determine the all models average and sd for each year / basin / variable.
# Calculate the upper and lower bounds of the distribution.
data %>%
  group_by(year, variable, basin) %>%
  summarise(amp_mean = mean(amplitude), amp_sd = sd(amplitude)) %>%
  mutate(lower_bound = amp_mean - amp_sd, upper_bound = amp_mean + amp_sd) %>%
  ungroup ->
  amp_sum_stats

# Join the model average and sd by year / basin / variable. Create an indicator
# variable for weather of not the observation falls within the sameness
# distribution. Latter on that indicator variable will be quantified as a percent value.
data %>%
  left_join(amp_sum_stats, by = c("year", "variable", "basin")) %>%
  # Use 1 and 0 as logical indicators in wich 1 = TRUE and 0 = FALSE
  mutate(within = if_else(lower_bound <= amplitude & amplitude <= upper_bound, 1, 0)) %>%
  mutate(above_bounds = if_else(amplitude > upper_bound, 1, 0)) %>%
  mutate(below_bounds = if_else(amplitude < lower_bound, 1, 0)) ->
  amp_robustness_df


# Calculate the different percents, I think that the most common one will be the binary percent
# within/out the distribution but the above or below may be interesting as well, but I don't
# really know. I will calculate them anyway.
#
# Find the number of counts for observations and the three indicator variables. These counts will
# be used to calculate the percent of the observations.
amp_robustness_df %>%
  group_by(model, variable, basin) %>%
  summarise(within_count = sum(within),
            above_bounds_count = sum(above_bounds),
            below_bounds_count = sum(below_bounds),
            obs_count = n_distinct(year)) %>%
  ungroup ->
  amp_observations_count


# Convert the logical counts from counts to observations.
amp_observations_count %>%
  mutate(percent_within = 100 * within_count / obs_count,
         percent_above  = 100 * above_bounds_count / obs_count,
         percent_below  = 100 * below_bounds_count / obs_count) %>%
  select(model, variable, basin, percent_within, percent_above, percent_below) ->
  percent_robustness_df


# Line Graphs ------------------------------------------------------------------------------

# This section makes line graphs of the amplitude distribution, mean values, and
# single models at a time
#
# Start by selecting the the data to plot
amp_robustness_df %>%
  select(year, units, ensemble, experiment, variable, basin, model, amplitude,
         amp_mean, lower_bound, upper_bound) ->
  to_plot

# For each variable / basin create a robustness line graph.
to_plot %>%
  group_by(variable) %>%
  do(fig = vis.robustness(.)) ->
  robustness_figs_df

# Save the figures in a list named by the
robustness_figs <- setNames(object = robustness_figs_df$fig, nm = robustness_figs_df$variable)



# Sameness Kables ------------------------------------------------------------------------------

# Format the data to make into the table. Control the number of digits and
# select which percent to spread.

# Within the distribution percent kable
percent_robustness_df %>%
  mutate(percent_within = signif(percent_within, 3)) %>%
  select(basin, model, variable, percent_within) %>%
  spread(basin, percent_within) ->
  to_table

# Use the kable.robustness function to create the robustness kables
to_table %>%
  group_by(variable) %>%
  do(kable = kable.robustness(., "% within the distribution")) ->
  robustness_kable_df

within_distribution <- setNames(robustness_kable_df$kable, nm = robustness_kable_df$variable)


# Percent above the distribution
percent_robustness_df %>%
  mutate(percent_above = signif(percent_above, 3)) %>%
  select(basin, model, variable, percent_above) %>%
  spread(basin, percent_above) ->
  to_table

# Use the kable.robustness function to create the robustness kables
to_table %>%
  group_by(variable) %>%
  do(kable = kable.robustness(., "% above the distribution")) ->
  robustness_kable_df

above_distribution <- setNames(robustness_kable_df$kable, nm = robustness_kable_df$variable)



# Percent below the distribution
percent_robustness_df %>%
  mutate(percent_below = signif(percent_below, 3)) %>%
  select(basin, model, variable, percent_below) %>%
  spread(basin, percent_below) ->
  to_table

# Use the kable.robustness function to create the robustness kables
to_table %>%
  group_by(variable) %>%
  do(kable = kable.robustness(., "% blow the distribution")) ->
  robustness_kable_df

below_distribution <- setNames(robustness_kable_df$kable, nm = robustness_kable_df$variable)


# Percent Within Bar Plots ------------------------------------------------------------------------------

percent_robustness_df %>%
  ggplot(aes(x = basin, y = percent_within,  fill = model, group = model)) +
  geom_col(position = "dodge") +
  facet_wrap("variable") +
  MY_SETTINGS +
  labs(title = "Percent Within Robust Distribution \nby Model",
       y = "% of total amplitude time series within ") ->
  percent_within_bar


# Which Model(s) Most Consistent ------------------------------------------------------------------------

percent_robustness_df %>%
  select(model, variable, basin, percent_within) %>%
  group_by(basin, variable) %>%
  filter(percent_within == max(percent_within)) %>%
  ungroup %>%
  group_by(model) %>%
  summarise(count = n()) %>%
  arrange(count) %>%
  knitr::kable() ->
  count_within

percent_robustness_df %>%
  select(model, variable, basin, percent_within) %>%
  group_by(model) %>%
  summarise(mean = mean(percent_within)) %>%
  arrange(mean) %>%
  knitr::kable(digits = 2) ->
  mean_percent_within



# Final Formating and save Script Products --------------------------------------------------------------

out = list(within = within_distribution,
           above = above_distribution,
           below = below_distribution,
           figures = robustness_figs,
           fig_bar = percent_within_bar,
           count = count_within,
           mean = mean_percent_within)

save(out, file = paste0(OUTPUT_DIR,"/amplitude_sameness.rda"))

# Print the pdfs
if(please_print){

  pdf(paste0(OUTPUT_DIR,"/pdfs/amplitude_samenessFIGS.pdf"))

  for(i in 1:length(out$figures)){
    print(out$figures[i])
  }

  dev.off()

}



# End -----
message("script complete")



