# Purpose: This script looks at the observations for the complete data set.
#
# Created by: Dorheim, Kalyn
# Created on: October 11 2017
# Modified:   November 16 2017
#
# Notes: Still trying to figure out how the heck I can print out all of the figures saved in the
# list in the pdf
#
# Environment ------------------------------------------------------------------------------

# Required Libraries
devtools::load_all()
library(ggplot2)
library(dplyr)

# Define the directoires
INPUT_DIR  <- "data/cmip"
OUTPUT_DIR <- "figs/cmip"

# Print pdfs setting, if TRUE then all figures generated by this script will be printed as pdfs
# if FALSe will not. If set to FALSE the script will run faster.
print_pdf <- FALSE

# Script Functions ------------------------------------------------------------------------------

# I think this will be usefull will probably move it to the vis_fxns script
stats.year_labels <- function(data){

  data %>%
    dplyr::select(experiment, start_year, end_year) %>%
    dplyr::distinct() %>%
    dplyr::mutate(label = paste0(experiment, " : ", start_year, " - ", end_year)) %>%
    dplyr::select(label)

}


# Import Data ------------------------------------------------------------------------------

# Data paths
raw_path <- list.files(INPUT_DIR, "basin_mean.rda", full.names = TRUE)
detrended_path <- list.files(INPUT_DIR, "detrended_data.rda", full.names = TRUE)
summary_path   <- list.files(INPUT_DIR, "summary_stats.rda", full.names = TRUE)
amplitude_path <- list.files(INPUT_DIR, "amplitude.rda", full.names = TRUE)
extreme_path   <- list.files("data/cmip/", "max_min", full.names = TRUE)
KS_path <- list.files(INPUT_DIR, "Kurtosis_Skewness", full.names = TRUE)


# Load the data sets
raw_data <- get(load(raw_path))
detrended_data <- get(load(detrended_path))
summary_data   <- get(load(summary_path))
amplitude_data <- get(load(amplitude_path))
extreme_data   <- get(load(extreme_path))

# Load the list of the K and S dataframes, parse out the dataframes from the list
KS_list  <- get(load(KS_path))
KS_data  <- KS_list$K_S
delta_KS <- KS_list$delta_K_S


# Time Series Plots ------------------------------------------------------------------------------

# Raw time series
tseries_raw <- plot.time_series(raw_data)


# Detrended time series
tseries_detrended <- plot.time_series(detrended_data)


# Amplitude time series
# In order to plot annual seasonal amplitude change the column names to be compatible with the
# plot.time_series function
amplitude_data %>%
  rename(date = year, value = amplitude) %>%
  plot.time_series(subtitle = "Seasonal Amplitude", legend = FALSE) ->
  tseries_amplitude

amplitude_data %>%
  rename(date = year, value = min) %>%
  plot.time_series(subtitle = "Annual Min Value", legend = FALSE) ->
  tseries_min

amplitude_data %>%
  rename(date = year, value = max) %>%
  plot.time_series(subtitle = "Annual Max Value", legend = F) ->
  tseries_max




# Monthly Means ------------------------------------------------------------------------------
data <- tidyr::spread(summary_data, value_type, value)
mean_monthly = list()

var_list <- unique(data$variable)

for(i in 1:length(var_list)){

  to_plot   <- filter(data, variable == var_list[i])
  yr_labels <- stats.year_labels(to_plot)
  variable  <- unique(to_plot$variable)

  to_plot %>%
    group_by(month, month_name, experiment, ensemble, basin, units) %>%
    rename(value = mean) %>%
    summarise(mean = mean(value), sd = sd(value)) %>%
    ggplot(aes(x = month, y = mean, color = experiment)) +
    geom_line(size = 2) +
  #  geom_ribbon(aes(ymin = mean - 2*sd, ymax = mean + 2*sd, x = month, group = experiment, linetype=NA), alpha = 0.25) +
    facet_wrap(facets = "basin", ncol = 3, scale = "free") +
    theme(text = element_text(size = 13)) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  #  labs(title = "All-Models mean monthly with 2 sigma band",
  #       y = paste0("Mean Detrended ", variable),
    labs(title = "All-Models mean monthly", y = paste0("Mean Detrended ", variable),
         caption = paste0(yr_labels[1,], "\n", yr_labels[2,], "/n/n")) +
    scale_x_discrete(limits = to_plot$month, labels = to_plot$month_name) +
    oceanpH::MY_SETTINGS ->
    mean_monthly[[paste0(variable)]]

} # end of plotting for loop



# Amplitude Distribution ---------------------------------------------------------------------
amp_density_figs <- vis.amplitude_density(amplitude_data)


# K / S Scatter Plots ----------------------------------------------------------------------

# The K and S historical vs future K and S scatter plots, visualized by basin, variable,
# (and should probably add by model....)
KS_scatter_figs <- vis.KS_scatter_plots(KS_data)


# Delta K and S scatter plots
delta_KS_fig <- vis.delta_KS(delta_KS, boxplot = TRUE)



# Annual Extreme Heat Maps ----------------------------------------------------------------

# Start by calcualting the percent of max or min ocurring in each month by
# year / basin / variable. Count the number of observations in each month
# and divide by number of observations in each year.
extreme_data %>%
  group_by(year, basin, variable, month_name, value_type) %>%
  summarise(count = n()) %>%
  ungroup %>%
  group_by(year, basin, variable, value_type) %>%
  mutate(percent = 100 * count / sum(count)) %>%
  ungroup ->
  percent_data

# Since the percent_data only contains observations for the months of annual
# extemes the figures will not show a full 12 month annual cycle. In order to
# include all of the months in the figures, create at data frame for year 2101
# and add to the data frame to plot.
percent_data %>%
  select(basin, variable, value_type) %>%
  gcamdata::repeat_add_columns(tibble(month_name = MONTH_NAME$month_name)) %>%
  mutate(year = 2101, percent = NA) ->
  fake_2101

# Combine the percent_data and the fake 2101 observations in to a single data
# frame to plot.
fake_2101 %>%
  bind_rows(percent_data) ->
  percent_data_2101

# Order the months for plotting.
percent_data_2101$month_name <- factor(percent_data_2101$month_name, levels = rev(MONTH_NAME$month_name), ordered = TRUE)

# Make figures
extreme_figs <- vis.annual_extremes(percent_data_2101)




# Save Plots ------------------------------------------------------------------------------

# Combine the time series plots into a list
time_series = list(detrended = tseries_detrended, raw = tseries_raw, amplitude = tseries_amplitude,
                   min = tseries_min, max = tseries_max)

# Save all of the figures in a single list
all_models = list(time_series = time_series,
                  mean_monthly = mean_monthly,
                  distribution = amp_density_figs,
                  KS_scatter_figs = KS_scatter_figs,
                  delta_K = delta_KS_fig,
                  annual_extremes = extreme_figs)

# Save figures asll .rda object
save(all_models, file = paste0(OUTPUT_DIR, "/multiple_models_figures.rda"))


# Struggeling with how to print all of the figures out in pdf format which is a real shame...
# may be one day soon... will somethign taht can navigate various lenght of lists and print
# them out.


# End ----
message("Script complete")
